### ISSUE TITLE
Order of matching affects if the code is run

### ISSUE THREAD

**Issue by davidpelaez** [soveran/syro#26]
Hi,

we use Syro (3.0.1) in some of our internal services and I'm working on testing one of the routers. I noticed that if I do a match with `post` and inside that match a string the code isn't run with the request as expected. Now, if I put the string match first and the post match inside that it works as expected. Here's the structure of all matches in the router (I replaced the actual with dots but the matchers are in the same order and quantity):

```ruby
 Router = Syro.new(APIDeck) do

    # Create request
    post do
      ...
    end

    # List requests
    get do
        ...
    end

    on :id do

      # **** change the order of the following lines and it will not match
      # POST /:id/publish_estimates
      on "publish_estimates" do
        post do
            ...
        end
      end

      # View the request
      get do
        ...
      end

      # Modify a request
      put do
        ...
      end
    end # on :id

  end # Router
```

I searched the docs and I couldn't find anything related to this and I don't see why it shouldn't work. Is this a bug or something I'm ignoring about how the routing tree works?

Thanks for Syro btw! Simple & fast as we like it.

**Comment by soveran** [comment]
@davidpelaez Hi! The verb matchers (`post`, `get`, etc.) succeed when two conditions are met: the request method equals the verb matcher, and there's no path left to be consumed. That means inside a verb matcher it is impossible to match a path segment, because as soon as the verb matcher succeeds it means you are at the end of the path. (I wanted to point you to the section in the tutorial where this is explained, but it looks like the server is currently down...)

**Comment by davidpelaez** [comment]
Thanks for replying, I was suspecting it was something like this and not a bug!

**Comment by soveran** [comment]
Thank you for asking! I'll improve the docs to better explain this behavior. Btw, I'll be in Bogotá on October 9-14, so if I can help you in any way just let me know :-)

**Comment by davidpelaez** [comment]
That's great! Let's at least have coffee. I'll send you my info to your
email in a sec.




David Peláez Tamayo
Designer & Entrepreneur
