### ISSUE TITLE
RFC re: improving performance

### ISSUE THREAD

**Issue by chrisfrank** [soveran/syro#30]
Hi @soveran,

Thank you for such an elegant library. Syro is simpler than other tree-based routers I've used, and its Deck API is flexible enough that so far I don't miss anything.

Syro is already one of that fastest routers in the Ruby ecosystem, but I've prepared a patch that increases performance by 30-40% in benchmarks (and ~5% in my current application), without breaking any tests or changing much code. It works by dynamically defining a method to handle requests, instead of calling `instance_eval` on `@syro_code`. Under CRuby, at least, calling `instance_eval` expensive.

Here's a link to compare:

https://github.com/soveran/syro/compare/master...chrisfrank:master

Please let me know if it'd be okay to send a pull request, and again, thank you for such a great tool.

Here's the benchmark I'm running:

```ruby 
# bench.rb
require 'benchmark/ips'
require 'syro'
require_relative 'syro_sans_instance_eval'

syro_app = Syro.new do
  on 'hello' do
    on 'world' do
      get { res.text 'hello world' }
    end
  end
end

patched_app = SyroSansInstanceEval.new do
  on 'hello' do
    on 'world' do
      get { res.text 'hello world' }
    end
  end
end

Benchmark.ips do |bm|
  bm.report('syro') do
    syro_app.call({
      'REQUEST_METHOD' => 'GET',
      'PATH_INFO' => '/hello/world',
    })
  end

  bm.report('patched') do
    patched_app.call({
      'REQUEST_METHOD' => 'GET',
      'PATH_INFO' => '/hello/world',
    })
  end

  bm.compare!
end
```

And the results:
```
Warming up --------------------------------------
                syro    14.117k i/100ms
             patched    18.661k i/100ms
Calculating -------------------------------------
                syro    154.614k (± 2.2%) i/s -    776.435k in   5.024502s
             patched    200.238k (± 2.2%) i/s -      1.008M in   5.035080s

Comparison:
             patched:   200237.9 i/s
                syro:   154613.8 i/s - 1.30x  slower
```

**Comment by soveran** [comment]
@chrisfrank This is excellent! I don't see any drawbacks at all, which makes this change even more amazing :-) I'm not home right now, so I will grab the code tonight just to double check, but I think we can create a pull request tomorrow and release a new version. I'm thinking if we can do:

```ruby
@deck.define_method(:syro_handle_request, &code)
```

And something else I'm thinking is what happens if we don't mark the method as private. What do you think?

Thanks a lot for this! I'll ping you tonight or tomorrow morning so we can plan the release.

**Comment by chrisfrank** [comment]
Glad it seems promising, and thanks for the fast response!

I marked the method private because it seemed like an implementation detail of `Deck#call`, but it certainly seems okay to leave it public instead.

Calling `@deck.define_method` instead of `@deck.send(:define_method, ...` would be great, but I think `define_method` was private in ruby < 2.5, so making that change would limit Syro to Ruby 2.5 and above. That would be fine for me, personally, but if the gem currently runs on older rubies, it seems better to maintain support.

**Comment by soveran** [comment]
I've found two small problems with this proposal, but I think we should merge this code even if we don't find suitable workarounds.

First, something that is not a problem but that could be convenient is to add a class method to `Syro::Deck` that wraps this logic of defining the method for dispatching the request. Let's say `Syro::Deck` defines a class method `implement`, then we can rewrite `Syro#initialize` like this:

```ruby
def initialize(deck = Deck, &code)
  @deck = deck.implement(&code)
end
```

A good side effect is that we can define and test decks independently, for instance:

```ruby
MyDeck.new.call(env, inbox)
```

That will behave like a Rack application.

The definition of `Syro::Deck.implement` could be like this:

```ruby
def self.implement(&code)
  Class.new(self) do
    define_method(:syro_handle_request, &code)
  end
end
```

Now, regarding the problems: one downside is the fact that `syro_handle_request` can be called from the app itself even if we mark it as private. By the way, I'm thinking about using `launch!` instead, to make it similar to `finish!`. If that name doesn't work, maybe we can call it `syro_dispatch!` and avoid having `handle` in the method name, just so that it doesn't look close to the other `handle` method. Regarding the problem that this method can be called, I think the only solution we have is to obfuscate the method name. I think `syro_something` should be enough, and probably even better if we add a bang, so `syro_dispatch!`, `syro_launch!` are candidates, as well as just `dispatch!` and `launch!`. In any case, this problem is not serious.

The other problem I see is that when an error occurs in the application, the report indicates that it happened in an anonymous class. For example, let's say the app calls the method `foo`, which doesn't exist. We would get this error:

```
#<NameError: undefined local variable or method `foo' for #<#<Class:0x00007fccd218c120>:0x00007fccd185bf60>>
```

The `#<#<Class:0x00007fccd218c120>:0x00007fccd185bf60>>` part is problematic when we have to debug.

One solution would be to define `inspect` in terms of the superclass, so a new version of `Syro::Deck.implement` could be something like this:

```ruby
def self.implement(&code)
  Class.new(self) do
    define_method(:launch!, &code)
    define_method(:inspect) { self.class.superclass }
  end
end
```

Now the same error would look like this:

```
#<NameError: undefined local variable or method `foo' for MyDeck:#<Class:0x00007fab7c176ce8>>
```

Or, with the default `Deck`:

```
#<NameError: undefined local variable or method `foo' for Syro::Deck:#<Class:0x00007fe4b7842b70>>
```

It's probably not perfect, but at least it points in the right direction.

As I mentioned before, the advantages of this patch outweight these issues. Let me know what you think, my guess is that we can decide on the best approach and if we are not satisfied with some part, we can document the trade off.

**Comment by chrisfrank** [comment]
These two issues seem valid to me, and the potential solutions you've outlined seem right. Should I work them into the fork and send a pull request?

Regarding the name of the new method, I like your suggestion of `syro_dispatch!`. To my ear, dispatching sounds like something that would happen on every request, whereas `launch!` sounds like something that would only happen on boot.

> Regarding the problem that this method can be called, I think the only solution we have is to obfuscate the method name.

Obfuscation is the only solution I can think of too. There's a sense, I guess, in which this isn't a new problem: a user can already call `instance_eval(&@syro_code)` from within an application and trigger an infinite stack error. Calling `syro_dispatch!` in app code would trigger the same problem. But because `syro_dispatch!` is less obscure than `instance_eval(&@syro_code)`, I do think it's a good idea to mark `syro_dispatch!` private. It won't actually prevent someone from calling it, but it may help signal that you shouldn't.

> something that is not a problem but that could be convenient is to add a class method to Syro::Deck that wraps this logic of defining the method for dispatching the request.

This seems like a good, clean way of encapsulating this behavior. Before I implement it, though, I just want to flag one edge case that could make this a breaking change, which doesn't arise using `@deck.send(:define_method)`:

If you've been running Syro with a custom Deck that doesn't subclass `Syro::Deck`, but instead just implements the needed parts of the Deck API on its own, this change would break your app. The fix would be to define `::implement` on your Deck according to the new spec.

This edge case might be so obscure that we shouldn't worry about it. Let me know what seems best to you and I'll get to work!

**Comment by soveran** [comment]
Agreed on the method name, `syro_dispatch!` has the advantages you mentioned. It is also true that people can sabotage themselves by calling `instance_eval(&@syro_code)`, I hadn't thought about that. About marking it private, I will let you decide. It won't be documented as part of the API, so I'm fine either way.

About the obscure edge case: you are absolutely right, that had also escaped me. But I agree that we shouldn't worry. I would say we can move forward!

If you can make those changes in your fork and send me a pull request, it would be ideal. We can check if the docs need to be updated and then we can release a new version and announce the performance increase :-)

Excellent work!
